import { Script } from '@script_types/script/script';
import { ScriptConfig } from '../gen/spec_config'; /* File will be automatically generated by compiler! Run "nom run cli install" */
import { Instance } from './main';

export class WorkerScript implements Script.Class<ScriptConfig> {
    
    private instance: Instance | undefined;

    start = async (ctx: Script.Context, config: ScriptConfig): Promise<void> => {
        this.instance = new Instance(ctx, config);
        this.instance.start();
    }

    stop = async (reason: Script.StopReason): Promise<void> => {
        console.info("Stopping all my stuff ...");
        return this.instance?.stop(reason);
    }
}

export const script = new WorkerScript();